= mob_suite

unofficial containerization of genomic software MOB-suite (https://github.com/phac-nml/mob-suite), with database

**Work in progress, untested at this point**

https://github.com/phac-nml/mob-suite
has docker image and singularity definition file, 
but on 2024-08 when I used the docker image it didn't work.

also, theirs dont have database needed by mob_init, 
I am running that inside the container so it i will be a fat container, with the db embeded in it, 
so mob_recon is ready to run

intenteded for use in HPC

--

pull as:

apptainer pull --name mob_recon docker://ghcr.io/tin6150/mob_suite:main


== adoc testing below, please ignore

----

adoc after 4 dash
text in vim appear blue

another line after empty line

* 1-bullet line
* 1-bullet line
** 2-bullet line
** 2-bullet line
  * indented 1-bullet line
  * indented 1-bullet line

----

after another 4 dash text color return to normal

* 1-bullet line
* 1-bullet line
** 2-bullet line
** 2-bullet line
  * indented 1-bullet line
  * indented 1-bullet line


~~~~

after 4~ vim show text as green
another line

another line after empty line

* 1-bullet line
* 1-bullet line
** 2-bullet line
** 2-bullet line
  * indented 1-bullet line
  * indented 1-bullet line


~~~~

after another 4~, exit the block

* 1-bullet line
* 1-bullet line
** 2-bullet line
** 2-bullet line
  * indented 1-bullet line
  * indented 1-bullet line


probably easier if use VScode and use their preview
